import type { SaveCheckpoint,SaveContext,SaveEnvelopeV1,SaveSlotId } from '../domain/save';
import { createEnvelope,parseImport,validateSaveEnvelope } from '../domain/save';
import type { SessionState } from '../domain/session';
import type { SaveRecord,SaveRepository,WriteResult } from '../platform/save-repository';
export interface SlotView{readonly slotId:SaveSlotId;readonly record:SaveRecord|null;readonly error?:string;readonly recoverable?:boolean}
export class SaveService{
  private records=new Map<SaveSlotId,SaveRecord>();private errors=new Map<SaveSlotId,string>();private recoveries=new Map<SaveSlotId,{previous:SaveEnvelopeV1;actualRevision:unknown}>();pending=0;
  constructor(readonly context:SaveContext,private readonly repository:SaveRepository){}
  async refresh():Promise<void>{this.pending+=1;try{this.records.clear();this.errors.clear();this.recoveries.clear();for(const record of await this.repository.list()){try{const current=validateSaveEnvelope(record.current,this.context);if(current.slotId!==record.slotId)throw new Error('Stored save has the wrong slot ID');let previous:SaveEnvelopeV1|undefined;if(record.previous)try{previous=validateSaveEnvelope(record.previous,this.context);}catch{/* A damaged fallback must not hide a valid current revision. */}this.records.set(record.slotId,{slotId:record.slotId,current,...(previous?{previous}:{})});}catch(error){this.errors.set(record.slotId,error instanceof Error?error.message:String(error));if(record.previous)try{this.recoveries.set(record.slotId,{previous:validateSaveEnvelope(record.previous,this.context),actualRevision:(record.current as SaveEnvelopeV1|undefined)?.storageRevision});}catch{}}}}finally{this.pending-=1;}}
  slots():readonly SlotView[]{return(['slot-1','slot-2','slot-3'] as const).map(slotId=>({slotId,record:this.records.get(slotId)??null,...(this.errors.has(slotId)?{error:this.errors.get(slotId)!}:{}),...(this.recoveries.has(slotId)?{recoverable:true}:{})}));}
  async save(slotId:SaveSlotId,checkpoint:SaveCheckpoint,session:SessionState):Promise<WriteResult>{const expected=this.records.get(slotId)?.current.storageRevision??0,envelope=createEnvelope(slotId,expected+1,this.context,checkpoint,session);this.pending+=1;try{const result=await this.repository.write(slotId,envelope,expected);if(result.kind==='written')this.records.set(slotId,result.record);else if(result.kind==='stale')await this.refresh();return result;}finally{this.pending-=1;}}
  async load(slotId:SaveSlotId):Promise<SaveEnvelopeV1>{this.pending+=1;try{const record=await this.repository.read(slotId);if(!record)throw new Error('That save slot is empty');const envelope=validateSaveEnvelope(record.current,this.context);if(envelope.slotId!==slotId)throw new Error('Stored save has the wrong slot ID');this.records.set(slotId,record);return envelope;}finally{this.pending-=1;}}
  import(bytes:Uint8Array):SaveEnvelopeV1{return parseImport(bytes,this.context);}
  async storeImport(slotId:SaveSlotId,candidate:SaveEnvelopeV1):Promise<WriteResult>{const expected=this.records.get(slotId)?.current.storageRevision??0,envelope=validateSaveEnvelope({...candidate,slotId,storageRevision:expected+1,savedAt:new Date().toISOString()},this.context);this.pending+=1;try{const result=await this.repository.write(slotId,envelope,expected);if(result.kind==='written')this.records.set(slotId,result.record);else if(result.kind==='stale')await this.refresh();return result;}finally{this.pending-=1;}}
  async recover(slotId:SaveSlotId):Promise<WriteResult>{const recovery=this.recoveries.get(slotId);if(!recovery)return{kind:'failed',reason:'unknown',message:'No valid previous revision is available'};this.pending+=1;try{const result=await this.repository.recoverPrevious(slotId,recovery.actualRevision);if(result.kind==='written'){this.records.set(slotId,result.record);this.recoveries.delete(slotId);this.errors.delete(slotId);}else if(result.kind==='stale')await this.refresh();return result;}finally{this.pending-=1;}}
  exportText(envelope:SaveEnvelopeV1):string{return JSON.stringify(validateSaveEnvelope(envelope,this.context),null,2)+'\n';}
  close():void{this.repository.close();}
}
