import type { SaveEnvelopeV1,SaveSlotId } from '../domain/save';
export interface SaveRecord{readonly slotId:SaveSlotId;readonly current:SaveEnvelopeV1;readonly previous?:SaveEnvelopeV1}
export type WriteResult={kind:'written';record:SaveRecord}|{kind:'stale';actualRevision:number}|{kind:'failed';reason:'unavailable'|'quota'|'aborted'|'unknown';message:string};
export type RemoveResult={kind:'removed'}|Exclude<WriteResult,{kind:'written'}>;
export interface SaveRepository{list():Promise<readonly SaveRecord[]>;read(slotId:SaveSlotId):Promise<SaveRecord|null>;write(slotId:SaveSlotId,envelope:SaveEnvelopeV1,expectedRevision:number):Promise<WriteResult>;recoverPrevious(slotId:SaveSlotId,expectedRevision:unknown):Promise<WriteResult>;remove(slotId:SaveSlotId,expectedRevision:number):Promise<RemoveResult>;close():void}
const DB='rpgameworks',STORE='saveSlots';
function failure(error:unknown):Extract<WriteResult,{kind:'failed'}>{const name=error instanceof DOMException?error.name:'';return{kind:'failed',reason:name==='QuotaExceededError'?'quota':name==='AbortError'?'aborted':name==='InvalidStateError'||name==='SecurityError'?'unavailable':'unknown',message:error instanceof Error?error.message:String(error)};}
const request=<T>(value:IDBRequest<T>):Promise<T>=>new Promise((resolve,reject)=>{value.onsuccess=()=>resolve(value.result);value.onerror=()=>reject(value.error??new Error('IndexedDB request failed'));});
export class IndexedDbSaveRepository implements SaveRepository{
  private database:Promise<IDBDatabase>|null=null;private readonly transactions=new Set<IDBTransaction>();constructor(private readonly factory:IDBFactory|undefined=globalThis.indexedDB){}
  private own(transaction:IDBTransaction):IDBTransaction{this.transactions.add(transaction);const release=()=>this.transactions.delete(transaction);transaction.addEventListener('complete',release,{once:true});transaction.addEventListener('abort',release,{once:true});return transaction;}
  private open():Promise<IDBDatabase>{if(this.database)return this.database;if(!this.factory)return Promise.reject(new DOMException('IndexedDB is unavailable','InvalidStateError'));this.database=new Promise((resolve,reject)=>{let open:IDBOpenDBRequest;try{open=this.factory!.open(DB,1);}catch(error){reject(error);return;}open.onupgradeneeded=()=>{if(!open.result.objectStoreNames.contains(STORE))open.result.createObjectStore(STORE,{keyPath:'slotId'});};open.onsuccess=()=>resolve(open.result);open.onerror=()=>reject(open.error??new Error('IndexedDB unavailable'));open.onblocked=()=>reject(new Error('IndexedDB upgrade is blocked by another tab'));});return this.database;}
  async list():Promise<readonly SaveRecord[]>{const db=await this.open(),tx=this.own(db.transaction(STORE,'readonly'));return await request(tx.objectStore(STORE).getAll()) as SaveRecord[];}
  async read(slotId:SaveSlotId):Promise<SaveRecord|null>{const db=await this.open(),tx=this.own(db.transaction(STORE,'readonly'));return(await request(tx.objectStore(STORE).get(slotId)) as SaveRecord|undefined)??null;}
  async write(slotId:SaveSlotId,envelope:SaveEnvelopeV1,expectedRevision:number):Promise<WriteResult>{
    try{const db=await this.open();return await new Promise(resolve=>{const tx=this.own(db.transaction(STORE,'readwrite')),store=tx.objectStore(STORE);let result:WriteResult|null=null;
      const get=store.get(slotId);get.onerror=()=>{result=failure(get.error);tx.abort();};get.onsuccess=()=>{const existing=get.result as SaveRecord|undefined,actual=existing?.current.storageRevision??0;if(actual!==expectedRevision){result={kind:'stale',actualRevision:actual};tx.abort();return;}const record:SaveRecord={slotId,current:envelope,...(existing?{previous:existing.current}:{})};const put=store.put(record);put.onerror=()=>{result=failure(put.error);};put.onsuccess=()=>{result={kind:'written',record};};};
      tx.oncomplete=()=>resolve(result??{kind:'failed',reason:'unknown',message:'Save transaction completed without a result'});tx.onabort=()=>resolve(result??failure(tx.error));tx.onerror=()=>{};
    });}catch(error){return failure(error);}
  }
  async recoverPrevious(slotId:SaveSlotId,expectedRevision:unknown):Promise<WriteResult>{
    try{const db=await this.open();return await new Promise(resolve=>{const tx=this.own(db.transaction(STORE,'readwrite')),store=tx.objectStore(STORE);let result:WriteResult|null=null;const get=store.get(slotId);
      get.onerror=()=>{result=failure(get.error);tx.abort();};get.onsuccess=()=>{const record=get.result as SaveRecord|undefined,actual=(record?.current as SaveEnvelopeV1|undefined)?.storageRevision;if(!record?.previous){result={kind:'failed',reason:'unknown',message:'No previous save revision is available'};tx.abort();return;}if(!Object.is(actual,expectedRevision)){result={kind:'stale',actualRevision:Number.isSafeInteger(actual)?Number(actual):0};tx.abort();return;}const revision=Math.max(record.previous.storageRevision,Number.isSafeInteger(actual)?Number(actual):0)+1,recovered={...record.previous,slotId,storageRevision:revision,savedAt:new Date().toISOString()},next:SaveRecord={slotId,current:recovered,previous:record.previous};const put=store.put(next);put.onerror=()=>{result=failure(put.error);};put.onsuccess=()=>{result={kind:'written',record:next};};};tx.oncomplete=()=>resolve(result??{kind:'failed',reason:'unknown',message:'Recovery transaction completed without a result'});tx.onabort=()=>resolve(result??failure(tx.error));tx.onerror=()=>{};
    });}catch(error){return failure(error);}
  }
  async remove(slotId:SaveSlotId,expectedRevision:number):Promise<RemoveResult>{
    try{const db=await this.open();return await new Promise(resolve=>{const tx=this.own(db.transaction(STORE,'readwrite')),store=tx.objectStore(STORE);let result:RemoveResult|null=null;const get=store.get(slotId);
      get.onerror=()=>{result=failure(get.error);tx.abort();};get.onsuccess=()=>{const record=get.result as SaveRecord|undefined,actual=record?.current.storageRevision??0;if(actual!==expectedRevision){result={kind:'stale',actualRevision:actual};tx.abort();return;}const deletion=store.delete(slotId);deletion.onerror=()=>{result=failure(deletion.error);};deletion.onsuccess=()=>{result={kind:'removed'};};};tx.oncomplete=()=>resolve(result??{kind:'failed',reason:'unknown',message:'Remove transaction completed without a result'});tx.onabort=()=>resolve(result??failure(tx.error));tx.onerror=()=>{};
    });}catch(error){return failure(error);}
  }
  close():void{for(const transaction of this.transactions)try{transaction.abort();}catch{/* It may have completed between enumeration and abort. */}this.transactions.clear();void this.database?.then(db=>db.close()).catch(()=>{});this.database=null;}
}
